// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRN1G_eOIvXfDoUMvVHjvrcGpc-R1q7fw',
    appId: '1:513182017291:web:6e93fda582a8584beba40e',
    messagingSenderId: '513182017291',
    projectId: 'flutterappfs-50d75',
    authDomain: 'flutterappfs-50d75.firebaseapp.com',
    storageBucket: 'flutterappfs-50d75.appspot.com',
    measurementId: 'G-Z32N56LLLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgadmAs0kq4zMvx9dJDPysgua1rp__C38',
    appId: '1:513182017291:android:53377076e7bd2428eba40e',
    messagingSenderId: '513182017291',
    projectId: 'flutterappfs-50d75',
    storageBucket: 'flutterappfs-50d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRezPbCw_ISTPTJmPyj7dg4HhWkPFgAJ0',
    appId: '1:513182017291:ios:68aecb40faebe188eba40e',
    messagingSenderId: '513182017291',
    projectId: 'flutterappfs-50d75',
    storageBucket: 'flutterappfs-50d75.appspot.com',
    iosClientId: '513182017291-aqa5sii0q6bus3r77gl7m0n1v5qa0oq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRezPbCw_ISTPTJmPyj7dg4HhWkPFgAJ0',
    appId: '1:513182017291:ios:68aecb40faebe188eba40e',
    messagingSenderId: '513182017291',
    projectId: 'flutterappfs-50d75',
    storageBucket: 'flutterappfs-50d75.appspot.com',
    iosClientId: '513182017291-aqa5sii0q6bus3r77gl7m0n1v5qa0oq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );
}
